# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder "..", "/home/vagrant/MAGMA5G"
  config.vm.box = "ubuntu/focal64"

  config.vm.define :magma5g, autostart: false do |magma5g|
    magma5g.vm.hostname = "magma5g"
    magma5g.vm.network "private_network", ip: "192.168.60.176", nic_type: "82540EM"
    magma5g.vm.network "private_network", ip: "192.168.129.74", nic_type: "82540EM"

    magma5g.vm.provider "virtualbox" do |vb|
      vb.name = "magma5g"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end
end